/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogarSistema.java
 *
 * Created on 06/12/2010, 18:09:53
 */
package boundary.Autenticacao;

import boudary.FormListaContatos;
import control.Control;
import javax.swing.JOptionPane;
import jdbc.CriadorDeSession;

/**
 *
 * @author Fernando
 */
public class LogarSistema extends javax.swing.JFrame {

    /**
     * Creates new form LogarSistema
     */
    public LogarSistema(FormListaContatos form) {
        initComponents();
        this.formContatos = form;
        tfLogin.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPnlLogin = new javax.swing.JLayeredPane();
        btRede = new javax.swing.JButton();
        lbFiguraAut = new javax.swing.JLabel();
        pnlCamposLogin = new javax.swing.JPanel();
        tfLogin = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        tfSenha = new javax.swing.JPasswordField();
        btEntrar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Contatos");
        setResizable(false);

        btRede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/Icones/rede32x32.png"))); // NOI18N
        btRede.setToolTipText("Alterar endereço IP do servidor");
        btRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRedeActionPerformed(evt);
            }
        });
        btRede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btRedeKeyPressed(evt);
            }
        });
        btRede.setBounds(280, 10, 40, 30);
        lPnlLogin.add(btRede, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbFiguraAut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/Icones/autenticacao.png"))); // NOI18N
        lbFiguraAut.setBounds(0, 0, 340, 50);
        lPnlLogin.add(lbFiguraAut, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tfLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLoginKeyPressed(evt);
            }
        });

        lbSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSenha.setText("Senha:");

        lbUsuario.setText("Usuário:");

        tfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSenhaKeyPressed(evt);
            }
        });

        btEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/Icones/logon.png"))); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEntrarMouseClicked(evt);
            }
        });
        btEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btEntrarKeyPressed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/Icones/logout32x32.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        btSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btSairKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlCamposLoginLayout = new javax.swing.GroupLayout(pnlCamposLogin);
        pnlCamposLogin.setLayout(pnlCamposLoginLayout);
        pnlCamposLoginLayout.setHorizontalGroup(
            pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCamposLoginLayout.createSequentialGroup()
                        .addGroup(pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbUsuario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSenha)
                            .addComponent(tfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCamposLoginLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        pnlCamposLoginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btEntrar, btSair});

        pnlCamposLoginLayout.setVerticalGroup(
            pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuario)
                    .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCamposLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCamposLogin.setBounds(10, 60, 320, 119);
        lPnlLogin.add(pnlCamposLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lPnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lPnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btEntrarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (validarLogin()) {
                if (formContatos.logarSistema(tfLogin.getText(), String.valueOf(tfSenha.getPassword()))) {
                    tfSenha.setText("");
                    this.dispose();
                } else {
                    this.erroLogar();
                }
            }
        }
        if (evt.getKeyCode() == 27) {
            System.exit(0);
        }
    }//GEN-LAST:event_btEntrarKeyPressed

    private void btSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btSairKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            tfSenha.setText("");
            if (Control.getServerMode()) {
                CriadorDeSession.stopDatabase();
            }
            System.exit(0);
        }
        if (evt.getKeyCode() == 27) {
            System.exit(0);
        }
    }//GEN-LAST:event_btSairKeyPressed

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSairMouseClicked

    private void btEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEntrarMouseClicked
        // TODO add your handling code here:
        if (validarLogin()) {
            if (formContatos.logarSistema(tfLogin.getText(), String.valueOf(tfSenha.getPassword()))) {
                tfSenha.setText("");
                this.dispose();
            } else {
                this.erroLogar();
            }
        }
    }//GEN-LAST:event_btEntrarMouseClicked

    private void tfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (validarLogin()) {
                if (formContatos.logarSistema(tfLogin.getText(), String.valueOf(tfSenha.getPassword()))) {
                    tfSenha.setText("");
                    this.dispose();
                } else {
                    this.erroLogar();
                }
            }
        }
        if (evt.getKeyCode() == 27) {
            System.exit(0);
        }
    }//GEN-LAST:event_tfSenhaKeyPressed

    private void tfLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLoginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (validarLogin()) {
                if (formContatos.logarSistema(tfLogin.getText(), String.valueOf(tfSenha.getPassword()))) {
                    tfSenha.setText("");
                    this.dispose();
                } else {
                    this.erroLogar();
                }
            }
        }
        if (evt.getKeyCode() == 27) {
            System.exit(0);
        }
    }//GEN-LAST:event_tfLoginKeyPressed

    private void btRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRedeActionPerformed
        // TODO add your handling code here:
        FormRede formRede = new FormRede(this, false);
        formRede.setLocationRelativeTo(null);
        formRede.setVisible(true);
    }//GEN-LAST:event_btRedeActionPerformed

    private void btRedeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btRedeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 27) {
            System.exit(0);
        }
    }//GEN-LAST:event_btRedeKeyPressed

    private boolean validarLogin() {
        String login = "", senha = "";
        login = tfLogin.getText();
        senha = String.valueOf(tfSenha.getPassword());
        if (login.equals("")) {
            tfLogin.requestFocus();
            JOptionPane.showMessageDialog(null, "Digite o login", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (senha.equals("")) {
            tfSenha.requestFocus();
            JOptionPane.showMessageDialog(null, "Digite a senha", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void erroLogar() {
        tfSenha.setText("");
        tfSenha.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btRede;
    private javax.swing.JButton btSair;
    private javax.swing.JLayeredPane lPnlLogin;
    private javax.swing.JLabel lbFiguraAut;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel pnlCamposLogin;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables
    private final FormListaContatos formContatos;
}
