/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boudary;

import control.Control;
import domain.Cidade;
import domain.Contato;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import util.BloquearCampos;
import util.FixedLengthDocument;

/**
 *
 * @author Newcolor
 */
public class FormCadastroContatos extends javax.swing.JDialog {

    private int tipoOperacao;
    private Contato contato;
    private FormListaContatos formListCont;

    /**
     * Creates new form FormCadastroContatos
     */
    public FormCadastroContatos(FormListaContatos parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formListCont = parent;
    }

    FormCadastroContatos(FormListaContatos parent, boolean modal, int tipoOp, Contato cont) {
        super(parent, modal);
        initComponents();

        formListCont = parent;
        contato = cont;
        tipoOperacao = tipoOp;
        setarContato(contato);

        if (tipoOperacao == 1) {
            btAction.setText("Alterar");
        } else if (tipoOperacao == 2) {
            btAction.setText("Remover");
            BloquearCampos.bloqueiaCampo(this);
        } else if (tipoOperacao == 3) {
            BloquearCampos.bloqueiaCampo(this);
            btAction.setText("Fechar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastro = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbUF = new javax.swing.JLabel();
        lbInfo = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbFax = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfInfo = new javax.swing.JTextArea();
        tfEndereco = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        cbUF = new javax.swing.JComboBox();
        tfTelefone = new javax.swing.JFormattedTextField();
        tfFax = new javax.swing.JFormattedTextField();
        tfCelular = new javax.swing.JFormattedTextField();
        cbCidade = new javax.swing.JComboBox();
        btAction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Contatos");
        setModal(true);
        setResizable(false);

        pnlCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCodigo.setText("Código:");

        lbNome.setText("Nome:");

        lbEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEndereco.setText("Endereço:");

        jLabel4.setText("Complemento:");

        lbBairro.setText("Bairro:");

        lbCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCidade.setText("Cidade:");

        lbUF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUF.setText("UF:");

        lbInfo.setText("Informações Adicionais:");

        lbTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTelefone.setText("Telefone:");

        lbFax.setText("Fax:");

        lbCelular.setText("Celular:");

        tfCodigo.setEditable(false);
        tfCodigo.setFocusable(false);

        tfNome.setDocument(new FixedLengthDocument(100));
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        tfInfo.setColumns(20);
        tfInfo.setDocument(new FixedLengthDocument(250));
        tfInfo.setLineWrap(true);
        tfInfo.setRows(5);
        jScrollPane1.setViewportView(tfInfo);

        tfEndereco.setDocument(new FixedLengthDocument(50));

        tfComplemento.setDocument(new FixedLengthDocument(100));

        tfBairro.setDocument(new FixedLengthDocument(35));

        cbUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selecione--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbUF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFItemStateChanged(evt);
            }
        });

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        try {
            tfFax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfFax.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfFax.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfCelular.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        cbCidade.setEnabled(false);

        btAction.setText("Salvar");
        btAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(btAction, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addComponent(lbInfo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbUF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfComplemento)
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(tfEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbFax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlCadastroLayout.createSequentialGroup()
                                .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBairro)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUF)
                    .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(lbFax)
                    .addComponent(lbCelular)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionActionPerformed
        // TODO add your handling code here:
        if (tipoOperacao == 1) {
            alterarContato();
        } else if (tipoOperacao == 2) {
            removerContato();
        } else if (tipoOperacao == 3) {
            this.dispose();
        } else {
            inserirContato();
        }
    }//GEN-LAST:event_btActionActionPerformed

    private void cbUFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFItemStateChanged
        // TODO add your handling code here:
        if (cbUF.getSelectedIndex() != 0) {
            ArrayList<Cidade> cidades = new ArrayList<Cidade>();
            Iterator<Cidade> iteratorCidade;
            cbCidade.removeAllItems();
            cbCidade.setSelectedItem("");
            cbCidade.setEnabled(true);

            String selecione = "--Selecione--";
            cbCidade.addItem(selecione);
            cbCidade.setSelectedIndex(0);

            Cidade cidade = new Cidade();
            String ufSelecionada;
            ufSelecionada = (String) cbUF.getSelectedItem();
            cidade.setUf(ufSelecionada);
            cidades = (ArrayList<Cidade>) Control.selecionarTodasCidadesPorUF(cidade);

            iteratorCidade = cidades.iterator();
            while (iteratorCidade.hasNext()) {
                Cidade cidadeEscolhida = new Cidade();
                cidadeEscolhida = (Cidade) iteratorCidade.next();
                this.cbCidade.addItem(cidadeEscolhida);
            }
        } else {
            cbCidade.removeAllItems();
            cbCidade.setSelectedItem("");
            cbCidade.setEnabled(false);
        }
    }//GEN-LAST:event_cbUFItemStateChanged

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
        // TODO add your handling code here:
        tfNome.setText(tfNome.getText().toUpperCase());
    }//GEN-LAST:event_tfNomeKeyReleased

    public void inserirContato() {
        if (validarForm()) {
            Contato cont = new Contato();
            cont.setNome(tfNome.getText());
            cont.setEndereco(tfEndereco.getText());
            cont.setBairro(tfBairro.getText());
            cont.setComplemento(tfComplemento.getText());
            cont.setCidade((Cidade) cbCidade.getSelectedItem());
            cont.setTelefone(getTel(tfTelefone.getText()));
            cont.setFax(getTel(tfFax.getText()));
            cont.setCelular(getTel(tfCelular.getText()));
            cont.setInfoAd(stringToHtml(tfInfo.getText()));

            if (Control.inserirContato(cont)) {
                JOptionPane.showMessageDialog(null, "Contato salvo com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
                formListCont.listarContatosPorCodigoNomeTelefone();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao salvar contato!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void alterarContato() {
        if (validarForm()) {
            Contato cont = new Contato();
            cont.setCodigo(Integer.parseInt(tfCodigo.getText()));
            cont.setNome(tfNome.getText());
            cont.setEndereco(tfEndereco.getText());
            cont.setBairro(tfBairro.getText());
            cont.setComplemento(tfComplemento.getText());
            cont.setCidade((Cidade) cbCidade.getSelectedItem());
            cont.setTelefone(getTel(tfTelefone.getText()));
            cont.setFax(getTel(tfFax.getText()));
            cont.setCelular(getTel(tfCelular.getText()));
            cont.setInfoAd(stringToHtml(tfInfo.getText()));

            if (Control.alterarContato(cont)) {
                JOptionPane.showMessageDialog(null, "Contato alterado com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
                formListCont.listarContatosPorCodigoNomeTelefone();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao alterar contato!", "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void removerContato() {
        Contato cont = new Contato();
        cont.setCodigo(Integer.parseInt(tfCodigo.getText()));
        cont.setNome(tfNome.getText());
        cont.setEndereco(tfEndereco.getText());
        cont.setBairro(tfBairro.getText());
        cont.setComplemento(tfComplemento.getText());
        cont.setCidade((Cidade) cbCidade.getSelectedItem());
        cont.setTelefone(getTel(tfTelefone.getText()));
        cont.setFax(getTel(tfFax.getText()));
        cont.setCelular(getTel(tfCelular.getText()));
        cont.setInfoAd(stringToHtml(tfInfo.getText()));

        if (Control.removerContato(cont)) {
            JOptionPane.showMessageDialog(null, "Contato removido com sucesso!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
            formListCont.listarContatosPorCodigoNomeTelefone();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao remover contato!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean validarForm() {
        if (tfNome.getText().length() != 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Insira o nome do contato!", "Atenção!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    public String getTel(String tel) {
        tel = tel.replace("(", "");
        tel = tel.replace(")", "");
        tel = tel.replace("-", "");
        tel = tel.replace(" ", "");
        tel = tel.trim();

        return tel;
    }

    private void setarContato(Contato cont) {
        tfCodigo.setText(String.valueOf(cont.getCodigo()));
        tfNome.setText(cont.getNome());
        tfEndereco.setText(cont.getEndereco());
        tfBairro.setText(cont.getBairro());
        tfComplemento.setText(cont.getComplemento());
        if (cont.getCidade() != null) {
            cbUF.setSelectedItem(cont.getCidade().getUf());
            cbCidade.setSelectedItem(cont.getCidade());
        }
        tfTelefone.setText(cont.getTelefone());
        tfFax.setText(cont.getFax());
        tfCelular.setText(cont.getCelular());
        tfInfo.setText(htmlToString(cont.getInfoAd()));
    }

    private String htmlToString(String text) {
        text = text.replace("<html>", "");
        text = text.replace("<br>", "\n");
        return text;
    }

    private String stringToHtml(String text) {
        if (text.length() == 0) {
            return "";
        } else {
            text = "<html>" + text;
            text = text.replace("\n", "<br>");
            return text;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAction;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox cbUF;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbFax;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbUF;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JFormattedTextField tfFax;
    private javax.swing.JTextArea tfInfo;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
