/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boudary;

import boudary.listar.ListarPorTelefone;
import boudary.listar.ListarTodasCidades;
import boundary.Autenticacao.LogarSistema;
import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import control.Control;
import domain.Contato;
import domain.Usuario;
import it.sauronsoftware.junique.AlreadyLockedException;
import it.sauronsoftware.junique.JUnique;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.nio.file.FileSystems;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import jdbc.CriadorDeSession;
import org.hibernate.Session;
import org.hibernate.exception.JDBCConnectionException;
//import util.ContatoTableModel;

/**
 *
 * @author Newcolor
 */
public class FormListaContatos extends javax.swing.JFrame {

    /**
     * Creates new form FormListaContatos
     */
    public FormListaContatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPesquisa = new javax.swing.JPanel();
        tfTelefone = new javax.swing.JFormattedTextField();
        lbTelefone = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        btFiltrar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        lbCount = new javax.swing.JLabel();
        scpTbContatos = new javax.swing.JScrollPane();
        tbContatos = new org.jdesktop.swingx.JXTable();
        mBarListar = new javax.swing.JMenuBar();
        mCadastros = new javax.swing.JMenu();
        itemCidades = new javax.swing.JMenuItem();
        mCadUsuarios = new javax.swing.JMenuItem();
        mPesquisa = new javax.swing.JMenu();
        itemPorTelefone = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Lista de Contatos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        tfTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTelefoneKeyPressed(evt);
            }
        });

        lbTelefone.setText("Telefone:");

        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNome.setText("Nome:");

        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        lbCodigo.setText("Código:");

        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoKeyPressed(evt);
            }
        });

        btFiltrar.setText("Filtrar");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPesquisaLayout = new javax.swing.GroupLayout(pnlPesquisa);
        pnlPesquisa.setLayout(pnlPesquisaLayout);
        pnlPesquisaLayout.setHorizontalGroup(
            pnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPesquisaLayout.createSequentialGroup()
                        .addComponent(lbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesquisaLayout.createSequentialGroup()
                        .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPesquisaLayout.setVerticalGroup(
            pnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaLayout.createSequentialGroup()
                .addGroup(pnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPesquisaLayout.createSequentialGroup()
                        .addGroup(pnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTelefone)
                            .addComponent(lbCodigo)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPesquisaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btVisualizar.setText("Visualizar");
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Remover");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        lbCount.setText("  Total de Registros:");

        tbContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbContatos.getTableHeader().setReorderingAllowed(false);
        tbContatos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbContatosMouseMoved(evt);
            }
        });
        scpTbContatos.setViewportView(tbContatos);

        mCadastros.setText("Cadastros");

        itemCidades.setText("Cidades");
        itemCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCidadesActionPerformed(evt);
            }
        });
        mCadastros.add(itemCidades);

        mCadUsuarios.setText("Usuários");
        mCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadUsuariosActionPerformed(evt);
            }
        });
        mCadastros.add(mCadUsuarios);

        mBarListar.add(mCadastros);

        mPesquisa.setText("Pesquisa");

        itemPorTelefone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemPorTelefone.setText("Por Telefone");
        itemPorTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPorTelefoneActionPerformed(evt);
            }
        });
        mPesquisa.add(itemPorTelefone);

        mBarListar.add(mPesquisa);

        setJMenuBar(mBarListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpTbContatos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btExcluir, btNovo, btVisualizar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpTbContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVisualizar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAlterar, btExcluir, btNovo, btVisualizar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        FormCadastroContatos cadastroContatos = new FormCadastroContatos(this, false);
        cadastroContatos.setLocationRelativeTo(null);
        cadastroContatos.setVisible(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void itemCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCidadesActionPerformed
        // TODO add your handling code here:
        ListarTodasCidades listarTodasCidades = new ListarTodasCidades(this, false);
        listarTodasCidades.setLocationRelativeTo(null);
        listarTodasCidades.setVisible(true);
    }//GEN-LAST:event_itemCidadesActionPerformed

    private void itemPorTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPorTelefoneActionPerformed
        // TODO add your handling code here:
        ListarPorTelefone listarPorTelefone = new ListarPorTelefone(this, false);
        listarPorTelefone.setLocationRelativeTo(null);
        listarPorTelefone.setVisible(true);
    }//GEN-LAST:event_itemPorTelefoneActionPerformed

    private void mCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadUsuariosActionPerformed
        // TODO add your handling code here:
        FormUsuario formUsuario = new FormUsuario(this, false);
        formUsuario.setLocationRelativeTo(null);
        formUsuario.setVisible(true);
    }//GEN-LAST:event_mCadUsuariosActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if (tbContatos.getSelectedRowCount() != 0) {
//            FormCadastroContatos cadastroContatos = new FormCadastroContatos(this, false, 1, tableModelContato.getValueAt(tbContatos.getSelectedRow()));
            FormCadastroContatos cadastroContatos = new FormCadastroContatos(this, false, 1, tableModel.getValue(tbContatos.getSelectedRow()));
            cadastroContatos.setLocationRelativeTo(null);
            cadastroContatos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um contato na tabela!", "Atenção!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (tbContatos.getSelectedRowCount() != 0) {
//            FormCadastroContatos cadastroContatos = new FormCadastroContatos(this, false, 2, tableModelContato.getValueAt(tbContatos.getSelectedRow()));
            FormCadastroContatos cadastroContatos = new FormCadastroContatos(this, false, 2, tableModel.getValue(tbContatos.getSelectedRow()));
            cadastroContatos.setLocationRelativeTo(null);
            cadastroContatos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um contato na tabela!", "Atenção!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        // TODO add your handling code here:
        if (tbContatos.getSelectedRowCount() != 0) {
//            FormCadastroContatos cadastroContatos = new FormCadastroContatos(this, false, 3, tableModelContato.getValueAt(tbContatos.getSelectedRow()));
            FormCadastroContatos cadastroContatos = new FormCadastroContatos(this, false, 3, tableModel.getValue(tbContatos.getSelectedRow()));
            cadastroContatos.setLocationRelativeTo(null);
            cadastroContatos.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um contato na tabela!", "Atenção!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
        // TODO add your handling code here:
        listarContatosPorCodigoNomeTelefone();
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void tfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listarContatosPorCodigoNomeTelefone();
        }
    }//GEN-LAST:event_tfCodigoKeyPressed

    private void tfTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listarContatosPorCodigoNomeTelefone();
        }
    }//GEN-LAST:event_tfTelefoneKeyPressed

    private void tfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listarContatosPorCodigoNomeTelefone();
        }
    }//GEN-LAST:event_tfNomeKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CriadorDeSession.getSession().close();
        if (Control.getServerMode()) {
            CriadorDeSession.stopDatabase();
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void tbContatosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContatosMouseMoved
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row = tbContatos.rowAtPoint(p);
//        tbContatos.setToolTipText(tableModelContato.getValueAt(row).getInfoAd());
        tbContatos.setToolTipText(tableModel.getValue(row).getInfoAd());
    }//GEN-LAST:event_tbContatosMouseMoved

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
        // TODO add your handling code here:
        tfNome.setText(tfNome.getText().toUpperCase());
    }//GEN-LAST:event_tfNomeKeyReleased

    public void listarContatosPorCodigoNomeTelefone() {
        int cod = 0;
        if (tfCodigo.getText().length() != 0) {
            cod = Integer.parseInt(tfCodigo.getText());
        }

        Contato contato = new Contato();
        contato.setCodigo(cod);
        contato.setNome(tfNome.getText());
        contato.setTelefone(getTel(tfTelefone.getText()));
        contato.setFax(getTel(tfTelefone.getText()));
        contato.setCelular(getTel(tfTelefone.getText()));

        contatos = (ArrayList<Contato>) Control.selecionarTodosContatosPorCodigoNomeTelefone(contato);

//        tableModelContato.setData(contatos);
        tableModel.setData(contatos);
        setCount(contatos.size());
    }

    public void listarPorTelefone(String tel) {
        Contato contato = new Contato();
        contato.setCodigo(0);
        contato.setNome("");
        contato.setTelefone(getTel(tel));
        contato.setFax(getTel(tel));
        contato.setCelular(getTel(tel));

        contatos = (ArrayList<Contato>) Control.selecionarTodosContatosPorCodigoNomeTelefone(contato);

//        tableModelContato.setData(contatos);
        tableModel.setData(contatos);
        setCount(contatos.size());
    }

    private void setCount(int count) {
        lbCount.setText("  Total de Registros: " + count);
    }

    private String getTel(String tel) {
        tel = tel.replace("(", "");
        tel = tel.replace(")", "");
        tel = tel.replace("-", "");
        tel = tel.replace(" ", "");
        tel = tel.trim();

        return tel;
    }

    private void formataColunas() {
        tbContatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite a seleção de somente uma linha
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        tbContatos.getColumnModel().getColumn(0).setCellRenderer(direita);

        tbContatos.getColumnModel().getColumn(0).setPreferredWidth(45);
        tbContatos.getColumnModel().getColumn(1).setPreferredWidth(380);
        tbContatos.getColumnModel().getColumn(2).setPreferredWidth(90);
        tbContatos.getColumnModel().getColumn(3).setPreferredWidth(90);
        tbContatos.getColumnModel().getColumn(4).setPreferredWidth(90);
    }
//    public void setarUsuario(Usuario usuario) {
//        tfNomeUsuario.setText(usuario.getNomeUsuario());
//    }

    public boolean logarSistema(String login, String senha) {
        try {
            // Abrinco conexão Hibernate com o banco de dados
            Session session = CriadorDeSession.getSession();

            if (session.isOpen()) {
                Control.setSession(session); // Setando a session na controladora

                Usuario usuario = new Usuario();
                usuario = Control.logarSistema(login, senha);
                if (usuario == null) {
                    JOptionPane.showMessageDialog(null, "Seu usuário e(ou) senha estão incorretos.\nPor favor digite-os corretamente.", "Erro!", JOptionPane.ERROR_MESSAGE);
                    return false;
                } else {
                    Control.setUsuario(usuario);
//                    this.setarUsuario(usuario);
                    this.setVisible(true);
                    //codigo para deixar maximizado
//                    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    preparaTabela();
                    return true;
                }
            } else {
                return false;
            }
        } catch (JDBCConnectionException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados!\nVerifique se o serviço está iniciado ou se o endereço IP do servidor está correto.", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void preparaTabela() {
        contatos = (ArrayList<Contato>) Control.selecionarTodosContatos();
        AnnotationResolver resolver = new AnnotationResolver(Contato.class);

        tableModel = new ObjectTableModel(resolver, "codigo,nome,telefone,fax,celular");

        tableModel.setData(contatos);
        tbContatos.setModel(tableModel);

//        tableModelContato = new ContatoTableModel(contatos);
//
//        tbContatos.setModel(tableModelContato);

        setCount(contatos.size());
        formataColunas();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListaContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
//        System.out.println(FileSystems.getDefault().getPath("").toAbsolutePath());
//        System.exit(0);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Garantindo que outra aplicação igual não será executada
                String appId = "Sistema Contatos";
                boolean alreadyRunning;
                try {
                    JUnique.acquireLock(appId);
                    alreadyRunning = false;
                } catch (AlreadyLockedException e) {
                    alreadyRunning = true;
                }
                if (!alreadyRunning) {
                    // Ícone do menu principal
//                    URL url = getClass().getResource("/boundary/Icones/Logo24x24.png");
//                    Image imagem = Toolkit.getDefaultToolkit().getImage(url);

                    FormListaContatos formListaContatos = new FormListaContatos();
                    formListaContatos.setLocationRelativeTo(null);
                    formListaContatos.setVisible(false);
//                    menuPrincipal.setIconImage(imagem); // Setando Ícone

                    LogarSistema logarSistema = null;
                    logarSistema = new LogarSistema(formListaContatos);
                    logarSistema.setLocationRelativeTo(null);
                    logarSistema.setVisible(true);
//                    logarSistema.setIconImage(imagem);
                } else {
                    JOptionPane.showMessageDialog(null, "A aplicação já esta em execução!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JMenuItem itemCidades;
    private javax.swing.JMenuItem itemPorTelefone;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCount;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JMenuBar mBarListar;
    private javax.swing.JMenuItem mCadUsuarios;
    private javax.swing.JMenu mCadastros;
    private javax.swing.JMenu mPesquisa;
    private javax.swing.JPanel pnlPesquisa;
    private javax.swing.JScrollPane scpTbContatos;
    private org.jdesktop.swingx.JXTable tbContatos;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Contato> contatos = new ArrayList<Contato>();
    ObjectTableModel<Contato> tableModel;
//    ContatoTableModel tableModelContato;
}
