/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListarTodosUsuariosPorCodigoNome.java
 *
 * Created on 15/12/2010, 10:36:39
 */
package boudary.listar;

import boudary.FormUsuario;
import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import control.Control;
import domain.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Fernando
 */
public class ListarTodosUsuariosPorCodigoNome extends javax.swing.JDialog {

    /** Creates new form ListarTodosUsuariosPorCodigoNome */
    public ListarTodosUsuariosPorCodigoNome(FormUsuario parent, boolean modal, String nomeUsuario) {
        super(parent, modal);
        initComponents();
        this.formUsuario = parent;
        URL url = getClass().getResource("/boundary/Icones/listarUsuarios16x16.png");
        Image imagem = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagem);

        Usuario usuario = new Usuario();
        usuario.setNomeUsuario(nomeUsuario);

        usuarios = (ArrayList<Usuario>) Control.selecionarTodosUsuariosPorCodigoNome(usuario);

        tfNome.setText(nomeUsuario);

        AnnotationResolver resolver = new AnnotationResolver(Usuario.class);

        tableModel = new ObjectTableModel<Usuario>(resolver, "codUsuario,nomeUsuario");

        tableModel.setData(usuarios);

        tbListarUsuarios.setModel(tableModel);
        this.formataColunas();
        lbStatus.setText("Total de Registros: " + usuarios.size());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlListarUsuarios = new javax.swing.JPanel();
        spListarUsuarios = new javax.swing.JScrollPane();
        tbListarUsuarios = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        lbCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Usuários");
        setModal(true);
        setResizable(false);

        pnlListarUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbListarUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbListarUsuarios.setToolTipText("Selecione a linha desejada e tecle Enter ou dê um duplo clique sobre ela");
        tbListarUsuarios.getTableHeader().setReorderingAllowed(false);
        tbListarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListarUsuariosMouseClicked(evt);
            }
        });
        tbListarUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbListarUsuariosKeyPressed(evt);
            }
        });
        spListarUsuarios.setViewportView(tbListarUsuarios);

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/Icones/pesquisar_Formulario.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPesquisarMouseClicked(evt);
            }
        });
        btPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btPesquisarKeyPressed(evt);
            }
        });

        lbCodigo.setText("Código:");

        tfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoKeyPressed(evt);
            }
        });

        lbNome.setText("Nome:");

        tfNome.setToolTipText("Digite o nome completo ou apenas parte dele para realizar a pesquisa");
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pnlListarUsuariosLayout = new javax.swing.GroupLayout(pnlListarUsuarios);
        pnlListarUsuarios.setLayout(pnlListarUsuariosLayout);
        pnlListarUsuariosLayout.setHorizontalGroup(
            pnlListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(spListarUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlListarUsuariosLayout.createSequentialGroup()
                        .addComponent(lbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar)))
                .addContainerGap())
        );
        pnlListarUsuariosLayout.setVerticalGroup(
            pnlListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarMouseClicked
        // TODO add your handling code here:
        if (!usuarios.isEmpty()) {
            for (int i = 0; i < usuarios.size(); i++) {
                tableModel.remove(i);
            }
        }

        int cod = 0;
        if (tfCodigo.getText().length() != 0) {
            cod = Integer.parseInt(tfCodigo.getText());
        }

        Usuario usuario = new Usuario();
        usuario.setCodUsuario(cod);
        usuario.setNomeUsuario(tfNome.getText());

        usuarios = (ArrayList<Usuario>) Control.selecionarTodosUsuariosPorCodigoNome(usuario);

        tableModel.setData(usuarios);
        lbStatus.setText("Total de Registros: " + usuarios.size());
}//GEN-LAST:event_btPesquisarMouseClicked

    private void btPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btPesquisarKeyPressed
        // TODO add your handling code here:
        this.pesquisarKeyPressed(evt);
    }//GEN-LAST:event_btPesquisarKeyPressed

    private void tfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyPressed
        // TODO add your handling code here:
        this.pesquisarKeyPressed(evt);
    }//GEN-LAST:event_tfNomeKeyPressed

    private void tfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoKeyPressed
        // TODO add your handling code here:
        this.pesquisarKeyPressed(evt);
    }//GEN-LAST:event_tfCodigoKeyPressed

    private void tbListarUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListarUsuariosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            formUsuario.setarUsuario(tableModel.getValue(tbListarUsuarios.getSelectedRow()));
            this.dispose();
        } else if (evt.getKeyCode() == 27) {
            this.dispose();
        }
}//GEN-LAST:event_tbListarUsuariosKeyPressed

    private void tbListarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListarUsuariosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            formUsuario.setarUsuario(tableModel.getValue(tbListarUsuarios.getSelectedRow()));
            this.dispose();
        }
}//GEN-LAST:event_tbListarUsuariosMouseClicked

    private void pesquisarKeyPressed (java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
            tableModel.clear();

            int cod = 0;
            if (tfCodigo.getText().length() != 0) {
                cod = Integer.parseInt(tfCodigo.getText());
            }

            Usuario usuario = new Usuario();
            usuario.setCodUsuario(cod);
            usuario.setNomeUsuario(tfNome.getText());

            usuarios = (ArrayList<Usuario>) Control.selecionarTodosUsuariosPorCodigoNome(usuario);

            tableModel.setData(usuarios);
            tbListarUsuarios.setModel(tableModel);
            lbStatus.setText("Total de Registros: " + usuarios.size());
        } else if (evt.getKeyCode() == 27) {
            this.dispose();
        }
    }

    private void formataColunas() {
        tbListarUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite a seleção de somente uma linha
        tbListarUsuarios.getColumnModel().getColumn(0).setPreferredWidth(45);
        tbListarUsuarios.getColumnModel().getColumn(0).setMaxWidth(55);
        tbListarUsuarios.getColumnModel().getColumn(0).setMinWidth(30);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JPanel pnlListarUsuarios;
    private javax.swing.JScrollPane spListarUsuarios;
    private javax.swing.JTable tbListarUsuarios;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Usuario> usuarios = new ArrayList<Usuario>();
    ObjectTableModel<Usuario> tableModel;
    FormUsuario formUsuario;
}
